# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c7104e63b3ccb2aae06cfe41a246bc32bf59beae516baa3164ba3f1a3c3a12fe3d46f42df077265d0f5d107f8e0dcd1718419ab4d1493a4c69a4084bf875c88

test:
  secret_key_base: ceb2a359fd78f0b09bf9fe03482f6a60cb32ba3163b35c070f7d1df7a3c94766f7bbf618a7b79da43b96b2ce30edf109a782d7adb92a884695afffb21146cf18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
